Write-Host "Vipers Installer`n`n`n`n`n`n`n"
Write-Host "Downloading MSI Afterburner & RTSS...`n"
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/vipe7/Vipers/master/MSI.exe" -OutFile "$env:userprofile\desktop\MSI.exe"
Write-Host "MSI Afterburner & RTSS downloaded`n"
Write-Host "Installing MSI Afterburner & RTSS...`n"
Start-Process -Wait -FilePath $env:userprofile\desktop\MSI.exe -ArgumentList '/S','/v','/qn' -passthru
Write-Host "`nMSI Afterburner & RTSS installed`n"
Write-Host "Removing downloaded files...`n"
Remove-Item "$env:userprofile\desktop\MSI.exe"
Remove-Item "$env:userprofile\desktop\MSI Afterburner.lnk"
Write-Host "Downloaded files removed`n"
Write-Host "Starting MSI Afterburner & RTSS...`n"
Start-Process -FilePath "RTSS.exe" -WorkingDirectory "C:\Program Files (x86)\RivaTuner Statistics Server"
Write-Host "ALL DONE`nPlease make MSI Afterburner and RTSS to start with Windows`nCheck step 2) Setting up MSI & TRSS"
Pause